version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1

    steps:
      - checkout

    dependencies:
      pre:
        - echo "export rvm_ignore_gemsets_flag=1" >> ~/.rvmrc
        - gem install bundler
        - gem install rspec

    test:
      post:
        - rspec
